<?php

/**
 * Címkezelő osztály
 */

// lehetőleg nagybetű, CamelCase - számmal nem kezdődhet
class Address {
    // publikus tulajdonság
    // címsor 1
    public $street_address_1;    
    // címsor 2
    public $street_address_2;    
    // ország
    public $country_name;    
    // város
    public $city_name;    
    // városrész
    public $subdivision_name;    
    //irányítószám
    public $postal_code;
}

